{% set name = "fido2" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3061cd05e73b3a0ef6afc3b803d57c826aa2d6a9732d16abd7277361f58e7964

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - cryptography

test:
  requires:
    - python {{ python_min }}
  imports:
    - fido2

about:
  home: https://pypi.org/project/fido2/
  summary: Fido2, functionality for communicating with a FIDO device over USB as well as verifying attestation and assertion signatures.
  license: BSD-2-Clause
  license_file: COPYING

extra:
  recipe-maintainers:
    - swainn
    - gagelarsen
