{% set name = "fido2" %}
{% set version = "2.1.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fido2-{{ version }}.tar.gz
  sha256: f1379f845870cc7fc64c7f07323c3ce41e8c96c37054e79e0acd5630b3fec5ac

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0
    - cryptography !=35,<49,>=2.6
    # - pyscard <3,>=1.9
    # - pyscard <3,>=1.9

test:
  requires:
    - python {{ python_min }}
  imports:
    - fido2

about:
  home: https://pypi.org/project/fido2/
  summary: Fido2, functionality for communicating with a FIDO device over USB as well as verifying attestation and assertion signatures.
  description: FIDO2/WebAuthn library for implementing clients and servers.
  license: Apache-2.0 AND BSD-2-Clause AND MPL-2.0
  license_file:
    - COPYING.MPLv2
    - COPYING.APLv2
    - COPYING

extra:
  recipe-maintainers:
    - swainn
    - gagelarsen
