{% set name = "fido2" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6110d913106f76199201b32d262b2857562cc46ba1d0b9c51fbce30dc936c573

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core
    - python >=3.7
  run:
    - python >=3.7
    - cryptography

test:
  imports:
    - fido2

about:
  home: https://pypi.org/project/fido2/
  summary: Fido2, functionality for communicating with a FIDO device over USB as well as verifying attestation and assertion signatures.
  license: BSD-2-Clause
  license_file: COPYING

extra:
  recipe-maintainers:
    - swainn
    - gagelarsen
