{% set name = "fido2" %}
{% set version = "0.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b45e89a6109cfcb7f1bb513776aa2d6408e95c4822f83a253918b944083466ec

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - six

test:
  imports:
    - fido2

about:
  home: https://pypi.org/project/fido2/
  summary: Fido2, functionality for communicating with a FIDO device over USB as well as verifying attestation and assertion signatures.
  license: BSD-2-Clause
  license_file: COPYING

extra:
  recipe-maintainers:
    - swainn
    - gagelarsen
