{% set name = "fido2" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 449068f6876f397c8bb96ebc6a75c81c2692f045126d3f13ece21d409acdf7c3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - six

test:
  imports:
    - fido2

about:
  home: https://pypi.org/project/fido2/
  summary: Fido2, functionality for communicating with a FIDO device over USB as well as verifying attestation and assertion signatures.
  license: BSD-2-Clause
  license_file: COPYING

extra:
  recipe-maintainers:
    - swainn
    - gagelarsen
